/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/amongus.gltf --transform 
Files: ./public/models/amongus.gltf [5.68KB] > C:\Users\Vanessa\Downloads\r3f-portfolio-final\amongus-transformed.glb [23.17KB] (-308%)
Author: DemonFawwn (https://sketchfab.com/demonfawwn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/miku-amongus-5a6253916afe46cdb1841ad513a90e00
Title: miku amongus
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/amongus-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder13_blinn1_0.geometry} material={materials.blinn1} />
      <mesh geometry={nodes.pCube4_lambert4_0.geometry} material={materials.lambert4} />
    </group>
  )
}

useGLTF.preload('/amongus-transformed.glb')
